Add pyproject.toml for Custom Node Registry
Danand/ComfyUI-ComfyCouple pull request #4
Opened 2024-06-14 08:09 UTC by haohaocreates

We are building a global registry for custom nodes (similar to PyPI). The registry makes using custom nodes more reliable by reserving globally unique names for each custom node, and supporting semantic versioning.

Here’s some [more information](https://comfydocs.org/registry/overview#introduction) on the registry.

Action Required:

- [ ] Go to the [registry](https://comfyregistry.org/). Login and create a publisher id. Comment it here and we will update the PR (or just merge it and change it yourself).
- [ ] Write a short the description.
- [ ] Merge the separate Github Actions PR and run the workflow.

If you want to publish the node manually, [install the cli](https://comfydocs.org/comfy-cli/getting-started#install-cli) and run `comfy node publish`
Please message me on [Discord](https://discord.com/invite/comfyorg) if you have any questions!

2024-06-20 13:04 UTC, haohaocreates commented
hey @Danand, wanted to send a small nudge and ask if you had any questions!

2024-06-28 03:07 UTC, haohaocreates commented
@Danand, wondering if there's any way we can support you on this PR!

2024-07-02 21:56 UTC, Danand commented
@haohaocreates 
Hi! Sorry for the delayed reply. I will check it out soon. Thank you!

2024-07-04 05:24 UTC, Danand requested changes

2024-07-04 05:24 UTC, Danand commented on pyproject.toml
> +license = "LICENSE"
```suggestion
license = "GPL-3.0"
```

2024-07-04 05:24 UTC, Danand commented on pyproject.toml
> +PublisherId = ""
```suggestion
PublisherId = "rei---"
```

2024-07-04 05:24 UTC, Danand commented on pyproject.toml
> +#  Used by Comfy Registry https://comfyregistry.org
```suggestion
```

2024-07-16 21:38 UTC, Danand approved these changes

2024-07-16 21:39 UTC, merged